import { DataSource } from 'typeorm';
import {
  Customer,
  CustomerType,
} from '../../modules/customers/entities/customer.entity';
import {
  Vehicle,
  VehicleStatus,
  FuelType,
} from '../../modules/vehicles/entities/vehicle.entity';
import {
  ServiceOrder,
  ServiceOrderStatus,
  ServiceOrderPriority,
} from '../../modules/service-orders/entities/service-order.entity';
import {
  Part,
  PartCategory,
  PartStatus,
} from '../../modules/parts/entities/part.entity';
import * as bcrypt from 'bcrypt';
import { User, UserRole } from '../../modules/users/entities/user.entity';

export async function seedDatabase(dataSource: DataSource) {
  console.log('Rozpoczynam seed bazy danych...');

  const customerRepo = dataSource.getRepository(Customer);
  const vehicleRepo = dataSource.getRepository(Vehicle);
  const serviceOrderRepo = dataSource.getRepository(ServiceOrder);
  const partRepo = dataSource.getRepository(Part);
  const userRepo = dataSource.getRepository(User);

  // 1. Sprawdź czy już istnieją dane
  const existingCustomers = await customerRepo.count();
  if (existingCustomers > 0) {
    console.log('Baza już zawiera dane. Pomijam seed.');
    return;
  }

  // 2. Pobierz mechaników (utworzonych przez user.seed.ts lub utwórz fallback)
  let mechanic = await userRepo.findOne({
    where: { email: 'mechanik@warsztat.pl' },
  });
  if (!mechanic) {
    // fallback gdyby user.seed nie został uruchomiony
    const hashedPassword = await bcrypt.hash('Mechanik123!', 12);
    mechanic = userRepo.create({
      email: 'mechanik@warsztat.pl',
      firstName: 'Piotr',
      lastName: 'Nowak',
      passwordHash: hashedPassword,
      role: UserRole.MECHANIC,
      phone: '987654321',
    });
    await userRepo.save(mechanic);
    console.log('Utworzono mechanika (fallback)');
  }

  let mechanic2 = await userRepo.findOne({
    where: { email: 'm.wroblewski@warsztat.pl' },
  });
  if (!mechanic2) {
    const hashedPassword = await bcrypt.hash('Mechanik123!', 12);
    mechanic2 = userRepo.create({
      email: 'm.wroblewski@warsztat.pl',
      firstName: 'Marek',
      lastName: 'Wróblewski',
      passwordHash: hashedPassword,
      role: UserRole.MECHANIC,
      phone: '111222333',
    });
    await userRepo.save(mechanic2);
  }

  let mechanic3 = await userRepo.findOne({
    where: { email: 'k.jablonski@warsztat.pl' },
  });
  if (!mechanic3) {
    const hashedPassword = await bcrypt.hash('Mechanik123!', 12);
    mechanic3 = userRepo.create({
      email: 'k.jablonski@warsztat.pl',
      firstName: 'Krzysztof',
      lastName: 'Jabłoński',
      passwordHash: hashedPassword,
      role: UserRole.MECHANIC,
      phone: '444555666',
    });
    await userRepo.save(mechanic3);
  }

  // 3. Utwórz klientów
  const customers = [
    // --- Osoby prywatne ---
    {
      type: CustomerType.INDIVIDUAL,
      firstName: 'Jan',
      lastName: 'Kowalski',
      email: 'jan.kowalski@example.com',
      phone: '+48 500 100 200',
      street: 'ul. Kwiatowa 15',
      postalCode: '00-001',
      city: 'Warszawa',
      pesel: '90010112345',
    },
    {
      type: CustomerType.INDIVIDUAL,
      firstName: 'Anna',
      lastName: 'Nowak',
      email: 'anna.nowak@example.com',
      phone: '+48 600 200 300',
      street: 'ul. Słoneczna 42',
      postalCode: '02-500',
      city: 'Warszawa',
    },
    {
      type: CustomerType.INDIVIDUAL,
      firstName: 'Maria',
      lastName: 'Zielińska',
      phone: '+48 510 400 500',
      city: 'Warszawa',
    },
    {
      type: CustomerType.INDIVIDUAL,
      firstName: 'Tomasz',
      lastName: 'Kaczmarek',
      email: 'tkaczmarek@example.com',
      phone: '+48 520 500 600',
      street: 'ul. Długa 88',
      postalCode: '03-200',
      city: 'Warszawa',
    },
    {
      type: CustomerType.INDIVIDUAL,
      firstName: 'Magdalena',
      lastName: 'Wójcik',
      email: 'm.wojcik@example.com',
      phone: '+48 530 600 700',
      street: 'ul. Różana 7',
      postalCode: '04-100',
      city: 'Warszawa',
      pesel: '85052012345',
    },
    {
      type: CustomerType.INDIVIDUAL,
      firstName: 'Rafał',
      lastName: 'Lewandowski',
      email: 'r.lewandowski@example.com',
      phone: '+48 540 700 800',
      street: 'ul. Lipowa 23',
      postalCode: '05-200',
      city: 'Legionowo',
    },
    {
      type: CustomerType.INDIVIDUAL,
      firstName: 'Agnieszka',
      lastName: 'Kamińska',
      email: 'a.kaminska@example.com',
      phone: '+48 550 800 900',
      street: 'ul. Chabrowa 11',
      postalCode: '02-300',
      city: 'Warszawa',
      pesel: '92031512345',
    },
    {
      type: CustomerType.INDIVIDUAL,
      firstName: 'Michał',
      lastName: 'Szymański',
      email: 'm.szymanski@example.com',
      phone: '+48 560 900 100',
      city: 'Pruszków',
    },
    {
      type: CustomerType.INDIVIDUAL,
      firstName: 'Beata',
      lastName: 'Woźniak',
      email: 'b.wozniak@example.com',
      phone: '+48 570 100 200',
      street: 'ul. Modrzewiowa 5',
      postalCode: '05-500',
      city: 'Piaseczno',
    },
    // --- Firmy ---
    {
      type: CustomerType.BUSINESS,
      firstName: 'Piotr',
      lastName: 'Wiśniewski',
      email: 'p.wisniewski@transbud.pl',
      phone: '+48 700 300 400',
      companyName: 'TransBud Sp. z o.o.',
      nip: '1234567890',
      street: 'ul. Przemysłowa 10',
      postalCode: '01-100',
      city: 'Warszawa',
    },
    {
      type: CustomerType.BUSINESS,
      firstName: 'Grzegorz',
      lastName: 'Majewski',
      email: 'kontakt@autoflota.pl',
      phone: '+48 710 400 500',
      companyName: 'AutoFlota Polska S.A.',
      nip: '9876543210',
      street: 'ul. Motoryzacyjna 44',
      postalCode: '02-200',
      city: 'Warszawa',
    },
    {
      type: CustomerType.BUSINESS,
      firstName: 'Dorota',
      lastName: 'Pawlak',
      email: 'biuro@expresslogistic.pl',
      phone: '+48 720 500 600',
      companyName: 'Express Logistic Sp. z o.o.',
      nip: '5544332211',
      street: 'ul. Logistyczna 3',
      postalCode: '05-800',
      city: 'Pruszków',
    },
    {
      type: CustomerType.BUSINESS,
      firstName: 'Andrzej',
      lastName: 'Kowalczyk',
      email: 'a.kowalczyk@taxi24.pl',
      phone: '+48 730 600 700',
      companyName: 'Taxi 24 Kowalczyk',
      nip: '1122334455',
      city: 'Warszawa',
    },
  ];

  const savedCustomers = await customerRepo.save(customers);
  console.log(`Utworzono ${savedCustomers.length} klientów`);
  const vehicles = [
    {
      customer: savedCustomers[0],
      customerId: savedCustomers[0].id,
      vin: '1HGBH41JXMN109186',
      brand: 'Toyota',
      model: 'Corolla',
      year: 2018,
      registrationNumber: 'WA 12345',
      fuelType: FuelType.PETROL,
      engineCapacity: 1600,
      enginePower: 132,
      mileage: 85000,
      color: 'Srebrny',
      status: VehicleStatus.ACTIVE,
    },

    {
      customer: savedCustomers[1],
      customerId: savedCustomers[1].id,
      vin: 'WVWZZZ1KZBW123456',
      brand: 'Volkswagen',
      model: 'Golf',
      year: 2020,
      registrationNumber: 'WA 67890',
      fuelType: FuelType.DIESEL,
      engineCapacity: 2000,
      enginePower: 150,
      mileage: 45000,
      color: 'Czarny',
      status: VehicleStatus.ACTIVE,
    },

    {
      customer: savedCustomers[2],
      customerId: savedCustomers[2].id,
      vin: 'SJNFAAZE1U1234567',
      brand: 'Nissan',
      model: 'Qashqai',
      year: 2021,
      registrationNumber: 'WA 22222',
      fuelType: FuelType.PETROL,
      engineCapacity: 1300,
      enginePower: 140,
      mileage: 25000,
      color: 'Czerwony',
      status: VehicleStatus.ACTIVE,
    },

    {
      customer: savedCustomers[3],
      customerId: savedCustomers[3].id,
      vin: 'JM1BK32F781234567',
      brand: 'Mazda',
      model: 'CX-5',
      year: 2022,
      registrationNumber: 'WA 33333',
      fuelType: FuelType.HYBRID,
      engineCapacity: 2500,
      enginePower: 194,
      mileage: 15000,
      color: 'Niebieski',
      status: VehicleStatus.ACTIVE,
    },

    {
      customer: savedCustomers[4],
      customerId: savedCustomers[4].id,
      vin: 'W0L000000N1234567',
      brand: 'Opel',
      model: 'Astra',
      year: 2017,
      registrationNumber: 'WA 44444',
      fuelType: FuelType.PETROL,
      engineCapacity: 1400,
      enginePower: 100,
      mileage: 112000,
      color: 'Szary',
      status: VehicleStatus.ACTIVE,
    },

    {
      customer: savedCustomers[5],
      customerId: savedCustomers[5].id,
      vin: 'TMBZZZ1Z0K1234567',
      brand: 'Skoda',
      model: 'Octavia',
      year: 2019,
      registrationNumber: 'WL 55555',
      fuelType: FuelType.DIESEL,
      engineCapacity: 2000,
      enginePower: 115,
      mileage: 68000,
      color: 'Biały',
      status: VehicleStatus.ACTIVE,
    },

    {
      customer: savedCustomers[6],
      customerId: savedCustomers[6].id,
      vin: 'WF0FXXGBBF1234567',
      brand: 'Ford',
      model: 'Focus',
      year: 2015,
      registrationNumber: 'WA 66666',
      fuelType: FuelType.PETROL,
      engineCapacity: 1600,
      enginePower: 105,
      mileage: 145000,
      color: 'Granatowy',
      status: VehicleStatus.ACTIVE,
    },

    {
      customer: savedCustomers[7],
      customerId: savedCustomers[7].id,
      vin: 'WAUZZZ8K0AA123456',
      brand: 'Audi',
      model: 'A4',
      year: 2016,
      registrationNumber: 'WP 77777',
      fuelType: FuelType.DIESEL,
      engineCapacity: 2000,
      enginePower: 177,
      mileage: 198000,
      color: 'Czarny',
      status: VehicleStatus.ACTIVE,
    },

    {
      customer: savedCustomers[7],
      customerId: savedCustomers[7].id,
      vin: 'JTMRFREV0HJ123456',
      brand: 'Toyota',
      model: 'RAV4',
      year: 2013,
      registrationNumber: 'WP 88888',
      fuelType: FuelType.PETROL,
      engineCapacity: 2000,
      enginePower: 151,
      mileage: 230000,
      color: 'Zielony',
      status: VehicleStatus.SOLD,
    },
    {
      customer: savedCustomers[8],
      customerId: savedCustomers[8].id,
      vin: 'VF1BB00YH12345678',
      brand: 'Renault',
      model: 'Clio',
      year: 2023,
      registrationNumber: 'WPI 9999',
      fuelType: FuelType.PETROL,
      engineCapacity: 1000,
      enginePower: 91,
      mileage: 8000,
      color: 'Pomarańczowy',
      status: VehicleStatus.ACTIVE,
    },
    {
      customer: savedCustomers[9],
      customerId: savedCustomers[9].id,
      vin: 'WDB9066571S123456',
      brand: 'Mercedes-Benz',
      model: 'Sprinter 316',
      year: 2020,
      registrationNumber: 'WA 11100',
      fuelType: FuelType.DIESEL,
      engineCapacity: 2200,
      enginePower: 163,
      mileage: 185000,
      color: 'Biały',
      status: VehicleStatus.ACTIVE,
    },
    {
      customer: savedCustomers[9],
      customerId: savedCustomers[9].id,
      vin: 'WDB9066571S789012',
      brand: 'Mercedes-Benz',
      model: 'Sprinter 316',
      year: 2021,
      registrationNumber: 'WA 11200',
      fuelType: FuelType.DIESEL,
      engineCapacity: 2200,
      enginePower: 163,
      mileage: 97000,
      color: 'Biały',
      status: VehicleStatus.ACTIVE,
    },
    {
      customer: savedCustomers[10],
      customerId: savedCustomers[10].id,
      vin: 'WBA5A2C54GG123456',
      brand: 'BMW',
      model: '5 Series',
      year: 2021,
      registrationNumber: 'WA 50010',
      fuelType: FuelType.PLUGIN_HYBRID,
      engineCapacity: 2000,
      enginePower: 252,
      mileage: 42000,
      color: 'Grafitowy',
      status: VehicleStatus.ACTIVE,
    },
    {
      customer: savedCustomers[11],
      customerId: savedCustomers[11].id,
      vin: 'WF0XXXTTGXHJ12345',
      brand: 'Ford',
      model: 'Transit',
      year: 2019,
      registrationNumber: 'WPR 1010',
      fuelType: FuelType.DIESEL,
      engineCapacity: 2000,
      enginePower: 130,
      mileage: 220000,
      color: 'Srebrny',
      status: VehicleStatus.ACTIVE,
    },
    {
      customer: savedCustomers[12],
      customerId: savedCustomers[12].id,
      vin: 'KM8J3CAL8HU123456',
      brand: 'Hyundai',
      model: 'Tucson',
      year: 2019,
      registrationNumber: 'WA 20200',
      fuelType: FuelType.LPG,
      engineCapacity: 1600,
      enginePower: 132,
      mileage: 310000,
      color: 'Czarny',
      status: VehicleStatus.ACTIVE,
    },
    {
      customer: savedCustomers[12],
      customerId: savedCustomers[12].id,
      vin: 'KM8J3CAL8HU789012',
      brand: 'Hyundai',
      model: 'Tucson',
      year: 2021,
      registrationNumber: 'WA 20201',
      fuelType: FuelType.LPG,
      engineCapacity: 1600,
      enginePower: 132,
      mileage: 182000,
      color: 'Czarny',
      status: VehicleStatus.ACTIVE,
    },
  ];

  const savedVehicles = await vehicleRepo.save(vehicles);
  console.log(`Utworzono ${savedVehicles.length} pojazdów`);

  const now = new Date();
  const d = (daysOffset: number) =>
    new Date(now.getTime() + daysOffset * 24 * 60 * 60 * 1000);

  const serviceOrders = [
    {
      orderNumber: 'ZL-2026-001',
      customer: savedCustomers[0],
      customerId: savedCustomers[0].id,
      vehicle: savedVehicles[0],
      vehicleId: savedVehicles[0].id,
      assignedMechanic: mechanic,
      assignedMechanicId: mechanic.id,
      description: 'Wymiana oleju i filtrów, kontrola zawieszenia',
      status: ServiceOrderStatus.IN_PROGRESS,
      priority: ServiceOrderPriority.HIGH,
      scheduledAt: d(-2),
      startedAt: d(-1),
      mileageAtAcceptance: 85000,
      laborCost: 200.0,
      partsCost: 350.0,
      totalCost: 550.0,
      mechanicNotes: 'Zawieszenie w dobrym stanie',
    },
    {
      orderNumber: 'ZL-2026-002',
      customer: savedCustomers[1],
      customerId: savedCustomers[1].id,
      vehicle: savedVehicles[1],
      vehicleId: savedVehicles[1].id,
      description: 'Przegląd roczny + wymiana klocków hamulcowych',
      status: ServiceOrderStatus.PENDING,
      priority: ServiceOrderPriority.NORMAL,
      scheduledAt: d(3),
      mileageAtAcceptance: 45000,
      laborCost: 150.0,
      partsCost: 280.0,
      totalCost: 430.0,
    },
    {
      orderNumber: 'ZL-2026-003',
      customer: savedCustomers[2],
      customerId: savedCustomers[2].id,
      vehicle: savedVehicles[2],
      vehicleId: savedVehicles[2].id,
      assignedMechanic: mechanic2,
      assignedMechanicId: mechanic2.id,
      description: 'Naprawa klimatyzacji, uzupełnienie płynu chłodzącego',
      status: ServiceOrderStatus.COMPLETED,
      priority: ServiceOrderPriority.URGENT,
      scheduledAt: d(-7),
      startedAt: d(-6),
      completedAt: d(-5),
      mileageAtAcceptance: 25000,
      laborCost: 300.0,
      partsCost: 850.0,
      totalCost: 1150.0,
      mechanicNotes: 'Wymieniono kompresor klimatyzacji',
    },
    {
      orderNumber: 'ZL-2026-004',
      customer: savedCustomers[3],
      customerId: savedCustomers[3].id,
      vehicle: savedVehicles[3],
      vehicleId: savedVehicles[3].id,
      description: 'Diagnostyka komputerowa + wymiana świec zapłonowych',
      status: ServiceOrderStatus.SCHEDULED,
      priority: ServiceOrderPriority.LOW,
      scheduledAt: d(7),
      mileageAtAcceptance: 15000,
      laborCost: 100.0,
      partsCost: 180.0,
      totalCost: 280.0,
    },
    {
      orderNumber: 'ZL-2026-005',
      customer: savedCustomers[4],
      customerId: savedCustomers[4].id,
      vehicle: savedVehicles[4],
      vehicleId: savedVehicles[4].id,
      assignedMechanic: mechanic,
      assignedMechanicId: mechanic.id,
      description: 'Wymiana tarcz i klocków hamulcowych wszystkie osie',
      status: ServiceOrderStatus.WAITING_FOR_PARTS,
      priority: ServiceOrderPriority.HIGH,
      scheduledAt: d(-1),
      startedAt: d(0),
      mileageAtAcceptance: 112000,
      laborCost: 400.0,
      partsCost: 1200.0,
      totalCost: 1600.0,
      mechanicNotes: 'Oczekiwanie na dostawę tarcz hamulcowych',
    },
    {
      orderNumber: 'ZL-2026-006',
      customer: savedCustomers[5],
      customerId: savedCustomers[5].id,
      vehicle: savedVehicles[5],
      vehicleId: savedVehicles[5].id,
      assignedMechanic: mechanic3,
      assignedMechanicId: mechanic3.id,
      description: 'Wymiana rozrządu, wymiana pompy wody',
      status: ServiceOrderStatus.IN_PROGRESS,
      priority: ServiceOrderPriority.HIGH,
      scheduledAt: d(-3),
      startedAt: d(-2),
      mileageAtAcceptance: 68000,
      laborCost: 800.0,
      partsCost: 650.0,
      totalCost: 1450.0,
      mechanicNotes: 'Komplet rozrządu w trakcie montażu',
    },
    {
      orderNumber: 'ZL-2026-007',
      customer: savedCustomers[6],
      customerId: savedCustomers[6].id,
      vehicle: savedVehicles[6],
      vehicleId: savedVehicles[6].id,
      description: 'Wymiana amortyzatorów przód',
      status: ServiceOrderStatus.PENDING,
      priority: ServiceOrderPriority.NORMAL,
      scheduledAt: d(5),
      mileageAtAcceptance: 145000,
      laborCost: 250.0,
      partsCost: 580.0,
      totalCost: 830.0,
    },
    {
      orderNumber: 'ZL-2026-008',
      customer: savedCustomers[7],
      customerId: savedCustomers[7].id,
      vehicle: savedVehicles[7],
      vehicleId: savedVehicles[7].id,
      assignedMechanic: mechanic2,
      assignedMechanicId: mechanic2.id,
      description: 'Regeneracja DPF, wymiana wtryskiwaczy',
      status: ServiceOrderStatus.IN_PROGRESS,
      priority: ServiceOrderPriority.URGENT,
      scheduledAt: d(-4),
      startedAt: d(-3),
      mileageAtAcceptance: 198000,
      laborCost: 1200.0,
      partsCost: 2800.0,
      totalCost: 4000.0,
      mechanicNotes: 'Wtryskiwacze mocno zużyte, czyszczenie ultrasoniczne',
    },
    {
      orderNumber: 'ZL-2026-009',
      customer: savedCustomers[9],
      customerId: savedCustomers[9].id,
      vehicle: savedVehicles[10],
      vehicleId: savedVehicles[10].id,
      assignedMechanic: mechanic,
      assignedMechanicId: mechanic.id,
      description: 'Przegląd 50 000 km – olej, filtry, hamulce, zawieszenie',
      status: ServiceOrderStatus.COMPLETED,
      priority: ServiceOrderPriority.NORMAL,
      scheduledAt: d(-14),
      startedAt: d(-14),
      completedAt: d(-13),
      mileageAtAcceptance: 185000,
      laborCost: 350.0,
      partsCost: 420.0,
      totalCost: 770.0,
      mechanicNotes: 'Klocki hamulcowe tył wymienione, reszta OK',
    },
    {
      orderNumber: 'ZL-2026-010',
      customer: savedCustomers[9],
      customerId: savedCustomers[9].id,
      vehicle: savedVehicles[11],
      vehicleId: savedVehicles[11].id,
      description: 'Naprawa zawieszenia – łączniki stabilizatora',
      status: ServiceOrderStatus.SCHEDULED,
      priority: ServiceOrderPriority.NORMAL,
      scheduledAt: d(10),
      mileageAtAcceptance: 97000,
      laborCost: 180.0,
      partsCost: 140.0,
      totalCost: 320.0,
    },
    {
      orderNumber: 'ZL-2026-011',
      customer: savedCustomers[10],
      customerId: savedCustomers[10].id,
      vehicle: savedVehicles[12],
      vehicleId: savedVehicles[12].id,
      assignedMechanic: mechanic3,
      assignedMechanicId: mechanic3.id,
      description:
        'Błąd check engine – diagnostyka + aktualizacja oprogramowania',
      status: ServiceOrderStatus.COMPLETED,
      priority: ServiceOrderPriority.HIGH,
      scheduledAt: d(-10),
      startedAt: d(-10),
      completedAt: d(-9),
      mileageAtAcceptance: 42000,
      laborCost: 400.0,
      partsCost: 0.0,
      totalCost: 400.0,
      mechanicNotes: 'Aktualizacja ECU rozwiązała problem',
    },
    {
      orderNumber: 'ZL-2026-012',
      customer: savedCustomers[11],
      customerId: savedCustomers[11].id,
      vehicle: savedVehicles[13],
      vehicleId: savedVehicles[13].id,
      assignedMechanic: mechanic,
      assignedMechanicId: mechanic.id,
      description: 'Wymiana sprzęgła, wymiana oleju skrzyni biegów',
      status: ServiceOrderStatus.WAITING_FOR_PARTS,
      priority: ServiceOrderPriority.HIGH,
      scheduledAt: d(-5),
      startedAt: d(-4),
      mileageAtAcceptance: 220000,
      laborCost: 900.0,
      partsCost: 1100.0,
      totalCost: 2000.0,
      mechanicNotes: 'Komplet sprzęgła zamówiony, dostawa jutro',
    },
    {
      orderNumber: 'ZL-2026-013',
      customer: savedCustomers[12],
      customerId: savedCustomers[12].id,
      vehicle: savedVehicles[14],
      vehicleId: savedVehicles[14].id,
      assignedMechanic: mechanic2,
      assignedMechanicId: mechanic2.id,
      description:
        'Przegląd + wymiana oleju silnikowego + instalacja LPG – przegląd',
      status: ServiceOrderStatus.CLOSED,
      priority: ServiceOrderPriority.NORMAL,
      scheduledAt: d(-20),
      startedAt: d(-20),
      completedAt: d(-19),
      mileageAtAcceptance: 310000,
      laborCost: 300.0,
      partsCost: 180.0,
      totalCost: 480.0,
      mechanicNotes: 'Instalacja LPG w dobrym stanie',
    },
    {
      orderNumber: 'ZL-2026-014',
      customer: savedCustomers[12],
      customerId: savedCustomers[12].id,
      vehicle: savedVehicles[15],
      vehicleId: savedVehicles[15].id,
      description: 'Wymiana opon sezonowych + wyważenie kół',
      status: ServiceOrderStatus.PENDING,
      priority: ServiceOrderPriority.LOW,
      scheduledAt: d(14),
      mileageAtAcceptance: 182000,
      laborCost: 80.0,
      partsCost: 0.0,
      totalCost: 80.0,
    },
    {
      orderNumber: 'ZL-2026-015',
      customer: savedCustomers[8],
      customerId: savedCustomers[8].id,
      vehicle: savedVehicles[9],
      vehicleId: savedVehicles[9].id,
      description: 'Pierwsze serwisowanie – wymiana oleju i filtra oleju',
      status: ServiceOrderStatus.SCHEDULED,
      priority: ServiceOrderPriority.NORMAL,
      scheduledAt: d(2),
      mileageAtAcceptance: 8000,
      laborCost: 120.0,
      partsCost: 90.0,
      totalCost: 210.0,
    },
    // --- Anulowane (do testów filtrów) ---
    {
      orderNumber: 'ZL-2026-016',
      customer: savedCustomers[1],
      customerId: savedCustomers[1].id,
      vehicle: savedVehicles[1],
      vehicleId: savedVehicles[1].id,
      description: 'Naprawa elektryki – falstart klienta',
      status: ServiceOrderStatus.CANCELLED,
      priority: ServiceOrderPriority.LOW,
      scheduledAt: d(-30),
      mileageAtAcceptance: 44500,
      laborCost: 0.0,
      partsCost: 0.0,
      totalCost: 0.0,
    },
  ];

  const savedOrders = await serviceOrderRepo.save(serviceOrders);
  console.log(`Utworzono ${savedOrders.length} zleceń serwisowych`);

  const parts = [
    {
      partNumber: 'FIL-OIL-001',
      name: 'Filtr oleju Mann W 712/75',
      description:
        'Filtr oleju silnikowego, pasuje do większości aut VW/Audi/Skoda z silnikami TSI/TFSI',
      category: PartCategory.FILTERS,
      manufacturer: 'Mann-Filter',
      brand: 'Mann',
      purchasePrice: 18.5,
      sellingPrice: 32.0,
      quantityInStock: 25,
      minStockLevel: 10,
      location: 'Regał A1',
      status: PartStatus.AVAILABLE,
      supplier: 'AutoParts Hurtownia',
      supplierEmail: 'zamowienia@autoparts.pl',
      supplierPhone: '+48 22 123 4567',
      compatibleVehicles:
        'VW Golf IV/V/VI, Audi A3, Skoda Octavia I/II, Seat Leon – silniki 1.4/1.6/1.8/2.0 TSI',
    },
    {
      partNumber: 'FIL-AIR-001',
      name: 'Filtr powietrza Mann C 2882',
      description: 'Filtr powietrza silnikowego',
      category: PartCategory.FILTERS,
      manufacturer: 'Mann-Filter',
      brand: 'Mann',
      purchasePrice: 22.0,
      sellingPrice: 38.0,
      quantityInStock: 18,
      minStockLevel: 8,
      location: 'Regał A1',
      status: PartStatus.AVAILABLE,
      supplier: 'AutoParts Hurtownia',
      supplierEmail: 'zamowienia@autoparts.pl',
      supplierPhone: '+48 22 123 4567',
      compatibleVehicles: 'Toyota Corolla E12/E13 2000-2008',
    },
    {
      partNumber: 'FIL-CAB-001',
      name: 'Filtr kabinowy węglowy Bosch 1987432416',
      category: PartCategory.FILTERS,
      manufacturer: 'Bosch',
      brand: 'Bosch',
      purchasePrice: 28.0,
      sellingPrice: 49.0,
      quantityInStock: 3,
      minStockLevel: 5,
      location: 'Regał A2',
      status: PartStatus.LOW_STOCK,
      supplier: 'Bosch Polska Sp. z o.o.',
      supplierEmail: 'sprzedaz@bosch.pl',
    },
    {
      partNumber: 'FIL-FUEL-001',
      name: 'Filtr paliwa Mahle KL 147',
      category: PartCategory.FILTERS,
      manufacturer: 'Mahle',
      brand: 'Mahle',
      purchasePrice: 35.0,
      sellingPrice: 58.0,
      quantityInStock: 12,
      minStockLevel: 5,
      location: 'Regał A2',
      status: PartStatus.AVAILABLE,
      supplier: 'AutoParts Hurtownia',
      supplierEmail: 'zamowienia@autoparts.pl',
    },
    {
      partNumber: 'OIL-5W30-001',
      name: 'Olej silnikowy Castrol Edge 5W-30 LL 4L',
      description: 'Syntetyczny olej silnikowy, norma VW 504/507',
      category: PartCategory.FLUIDS,
      manufacturer: 'Castrol',
      brand: 'Castrol',
      purchasePrice: 85.0,
      sellingPrice: 135.0,
      quantityInStock: 30,
      minStockLevel: 10,
      location: 'Regał B1',
      status: PartStatus.AVAILABLE,
      supplier: 'Castrol Polska',
      compatibleVehicles:
        'Wszystkie silniki benzynowe i diesel z normą VW 504.00/507.00',
    },
    {
      partNumber: 'OIL-5W40-001',
      name: 'Olej silnikowy Mobil 1 ESP 5W-40 4L',
      description: 'Olej w pełni syntetyczny',
      category: PartCategory.FLUIDS,
      manufacturer: 'Mobil',
      brand: 'Mobil',
      purchasePrice: 95.0,
      sellingPrice: 155.0,
      quantityInStock: 20,
      minStockLevel: 8,
      location: 'Regał B1',
      status: PartStatus.AVAILABLE,
      supplier: 'Motul/ExxonMobil Dystrybutor',
    },
    {
      partNumber: 'FLU-BRAKE-001',
      name: 'Płyn hamulcowy Ate Typ 200 DOT4 500ml',
      category: PartCategory.FLUIDS,
      manufacturer: 'ATE',
      brand: 'ATE',
      purchasePrice: 18.0,
      sellingPrice: 32.0,
      quantityInStock: 14,
      minStockLevel: 6,
      location: 'Regał B2',
      status: PartStatus.AVAILABLE,
    },
    {
      partNumber: 'FLU-COOL-001',
      name: 'Płyn chłodniczy G12++ koncentrat 1.5L',
      category: PartCategory.FLUIDS,
      manufacturer: 'Febi Bilstein',
      brand: 'Febi',
      purchasePrice: 22.0,
      sellingPrice: 38.0,
      quantityInStock: 8,
      minStockLevel: 5,
      location: 'Regał B2',
      status: PartStatus.AVAILABLE,
    },
    {
      partNumber: 'BRK-PAD-F001',
      name: 'Klocki hamulcowe przód Brembo P 85 020',
      description: 'Klocki hamulcowe ceramiczne, oś przednia',
      category: PartCategory.BRAKES,
      manufacturer: 'Brembo',
      brand: 'Brembo',
      purchasePrice: 95.0,
      sellingPrice: 165.0,
      quantityInStock: 8,
      minStockLevel: 4,
      location: 'Regał C1',
      status: PartStatus.AVAILABLE,
      supplier: 'Brembo Polska',
      compatibleVehicles: 'VW Golf V/VI/VII, Audi A3 8P/8V, Seat Leon 1P/5F',
    },
    {
      partNumber: 'BRK-PAD-R001',
      name: 'Klocki hamulcowe tył Brembo P 85 021',
      description: 'Klocki hamulcowe, oś tylna',
      category: PartCategory.BRAKES,
      manufacturer: 'Brembo',
      brand: 'Brembo',
      purchasePrice: 78.0,
      sellingPrice: 138.0,
      quantityInStock: 6,
      minStockLevel: 4,
      location: 'Regał C1',
      status: PartStatus.AVAILABLE,
      compatibleVehicles: 'VW Golf V/VI/VII, Audi A3 8P/8V',
    },
    {
      partNumber: 'BRK-DISC-F001',
      name: 'Tarcze hamulcowe przód 288mm Zimmermann',
      description: 'Tarcze wentylowane, para',
      category: PartCategory.BRAKES,
      manufacturer: 'Zimmermann',
      brand: 'Zimmermann',
      purchasePrice: 185.0,
      sellingPrice: 320.0,
      quantityInStock: 4,
      minStockLevel: 2,
      location: 'Regał C2',
      status: PartStatus.AVAILABLE,
      compatibleVehicles: 'VW Golf V/VI, Audi A3 8P 1.6/2.0 TDI',
    },
    {
      partNumber: 'BRK-DISC-R001',
      name: 'Tarcze hamulcowe tył 255mm Zimmermann',
      description: 'Tarcze pełne, para',
      category: PartCategory.BRAKES,
      manufacturer: 'Zimmermann',
      brand: 'Zimmermann',
      purchasePrice: 155.0,
      sellingPrice: 270.0,
      quantityInStock: 0,
      minStockLevel: 2,
      location: 'Regał C2',
      status: PartStatus.OUT_OF_STOCK,
      supplier: 'Parts4Cars',
      supplierEmail: 'info@parts4cars.pl',
      notes: 'Zamówione – dostawa w ciągu 3 dni roboczych',
    },
    {
      partNumber: 'SUS-SHCK-F001',
      name: 'Amortyzator przód Sachs 315 192',
      description: 'Amortyzator gazowy, oś przednia (lewa lub prawa)',
      category: PartCategory.SUSPENSION,
      manufacturer: 'Sachs',
      brand: 'Sachs',
      purchasePrice: 175.0,
      sellingPrice: 295.0,
      quantityInStock: 4,
      minStockLevel: 2,
      location: 'Regał D1',
      status: PartStatus.AVAILABLE,
      compatibleVehicles: 'Ford Focus MK2/MK3 2004-2011',
    },
    {
      partNumber: 'SUS-STAB-001',
      name: 'Łącznik stabilizatora przód Lemförder',
      description: 'Drążek stabilizatora, komplet lewa+prawa strona',
      category: PartCategory.SUSPENSION,
      manufacturer: 'Lemförder',
      brand: 'Lemförder',
      purchasePrice: 45.0,
      sellingPrice: 78.0,
      quantityInStock: 10,
      minStockLevel: 4,
      location: 'Regał D1',
      status: PartStatus.AVAILABLE,
      compatibleVehicles: 'Toyota Corolla E12 2001-2007, Auris E150',
    },
    {
      partNumber: 'SUS-ARM-001',
      name: 'Wahacz dolny przedni lewy Febi 44756',
      description: 'Wahacz z przegubem kulowym',
      category: PartCategory.SUSPENSION,
      manufacturer: 'Febi Bilstein',
      brand: 'Febi',
      purchasePrice: 220.0,
      sellingPrice: 380.0,
      quantityInStock: 2,
      minStockLevel: 2,
      location: 'Regał D2',
      status: PartStatus.LOW_STOCK,
      compatibleVehicles: 'BMW 3 Series E46 1998-2005',
    },
    {
      partNumber: 'ENG-BELT-001',
      name: 'Pasek rozrządu Contitech CT1028',
      description: 'Pasek zębaty rozrządu',
      category: PartCategory.ENGINE,
      manufacturer: 'ContiTech',
      brand: 'ContiTech',
      purchasePrice: 65.0,
      sellingPrice: 112.0,
      quantityInStock: 5,
      minStockLevel: 3,
      location: 'Regał E1',
      status: PartStatus.AVAILABLE,
      compatibleVehicles: 'Skoda Octavia 2.0 TDI, VW Golf VI 2.0 TDI 2009-2013',
    },
    {
      partNumber: 'ENG-TKIT-001',
      name: 'Komplet rozrządu Gates K025656XS',
      description: 'Komplet: pasek + rolki + pompa wody',
      category: PartCategory.ENGINE,
      manufacturer: 'Gates',
      brand: 'Gates',
      purchasePrice: 380.0,
      sellingPrice: 620.0,
      quantityInStock: 3,
      minStockLevel: 2,
      location: 'Regał E1',
      status: PartStatus.AVAILABLE,
      compatibleVehicles:
        'Skoda Octavia II 2.0 TDI 140KM 2004-2013, VW Golf V/VI 2.0 TDI',
    },
    {
      partNumber: 'ENG-PLUG-001',
      name: 'Świeca zapłonowa Bosch Iridium 0242235985',
      description: 'Świeca z elektrodą irydową, zestaw 4 szt.',
      category: PartCategory.ENGINE,
      manufacturer: 'Bosch',
      brand: 'Bosch',
      purchasePrice: 55.0,
      sellingPrice: 95.0,
      quantityInStock: 12,
      minStockLevel: 5,
      location: 'Regał E2',
      status: PartStatus.AVAILABLE,
      compatibleVehicles: 'Nissan Qashqai 1.2/1.6 DIG-T, Mazda CX-5 2.0L',
    },
    {
      partNumber: 'ENG-INJC-001',
      name: 'Wtryskiwacz paliwa Bosch 0445110369',
      description: 'Wtryskiwacz Common Rail piezoelektryczny',
      category: PartCategory.ENGINE,
      manufacturer: 'Bosch',
      brand: 'Bosch',
      purchasePrice: 650.0,
      sellingPrice: 980.0,
      quantityInStock: 0,
      minStockLevel: 1,
      location: 'Regał E3',
      status: PartStatus.OUT_OF_STOCK,
      supplier: 'Bosch Polska Sp. z o.o.',
      supplierEmail: 'sprzedaz@bosch.pl',
      compatibleVehicles: 'Audi A4 2.0 TDI 177KM, VW Passat B6/B7 2.0 TDI',
      notes: 'Część na zamówienie, czas dostawy 5-7 dni',
    },
    {
      partNumber: 'ELC-BAT-001',
      name: 'Akumulator Varta Blue Dynamic 60Ah 540A',
      description: 'Akumulator rozruchowy 12V 60Ah',
      category: PartCategory.ELECTRICAL,
      manufacturer: 'Varta',
      brand: 'Varta',
      purchasePrice: 220.0,
      sellingPrice: 340.0,
      quantityInStock: 5,
      minStockLevel: 3,
      location: 'Regał F1',
      status: PartStatus.AVAILABLE,
    },
    {
      partNumber: 'ELC-ALT-001',
      name: 'Alternator Valeo 436655 100A',
      description: 'Alternator regenerowany',
      category: PartCategory.ELECTRICAL,
      manufacturer: 'Valeo',
      brand: 'Valeo',
      purchasePrice: 420.0,
      sellingPrice: 680.0,
      quantityInStock: 1,
      minStockLevel: 1,
      location: 'Regał F2',
      status: PartStatus.LOW_STOCK,
      compatibleVehicles: 'Renault Clio III/IV 1.2/1.6, Nissan Micra K13',
    },
    {
      partNumber: 'TRN-CLTH-001',
      name: 'Sprzęgło Sachs 3000 954 021 komplet',
      description: 'Komplet sprzęgła: tarcza + docisk + łożysko wysprzęglające',
      category: PartCategory.TRANSMISSION,
      manufacturer: 'Sachs',
      brand: 'Sachs',
      purchasePrice: 480.0,
      sellingPrice: 780.0,
      quantityInStock: 2,
      minStockLevel: 1,
      location: 'Regał G1',
      status: PartStatus.AVAILABLE,
      compatibleVehicles: 'Ford Transit 2.0 TDCi 2016-, Ford Focus RS',
    },
    {
      partNumber: 'TIR-195-65R15',
      name: 'Opona letnia Michelin Energy Saver+ 195/65 R15',
      description: 'Opona sezonowa klasy premium, indeks 91V',
      category: PartCategory.TIRES,
      manufacturer: 'Michelin',
      brand: 'Michelin',
      purchasePrice: 290.0,
      sellingPrice: 420.0,
      quantityInStock: 8,
      minStockLevel: 4,
      location: 'Magazyn opon P1',
      status: PartStatus.AVAILABLE,
    },
    {
      partNumber: 'TIR-205-55R16',
      name: 'Opona zimowa Continental WinterContact TS 860 205/55 R16',
      description: 'Opona zimowa, indeks 91H',
      category: PartCategory.TIRES,
      manufacturer: 'Continental',
      brand: 'Continental',
      purchasePrice: 340.0,
      sellingPrice: 490.0,
      quantityInStock: 0,
      minStockLevel: 4,
      location: 'Magazyn opon P2',
      status: PartStatus.OUT_OF_STOCK,
      notes: 'Sezon zimowy zakończony – brak zamówień do września',
    },
    {
      partNumber: 'ENG-CARBR-OLD',
      name: 'Gaźnik Weber 32/36 DGAV (wycofany)',
      description: 'Gaźnik podwójny – produkcja zakończona',
      category: PartCategory.ENGINE,
      manufacturer: 'Weber',
      brand: 'Weber',
      purchasePrice: 0.0,
      sellingPrice: 0.0,
      quantityInStock: 0,
      minStockLevel: 0,
      status: PartStatus.DISCONTINUED,
      notes: 'Produkt wycofany ze sprzedaży – brak wsparcia',
    },
  ];

  const savedParts = await partRepo.save(parts);
  console.log(`Utworzono ${savedParts.length} części`);

  console.log('Seed zakończony pomyślnie!');
}
